---
title: "Exploratory Analysis"
author: "QMSS5069 Team 1"
date: "February 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries:
```{r, message=FALSE, warning=TRUE}
stopifnot(require(tidyverse))
```


### Import Data
```{r}
gss <- read.csv(file.choose()) # team_1_project/Data
```

### Clean and Subset Data
```{r}
## subset by those who never married
clean <- gss[which(gss$agewed >= 12 | gss$marital == 5), ]
table(gss$marital == 5)  # 1080 respondents who never married
table(clean$marital == 5)  # still 1080
table(clean$marital == 5, clean$agewed)  # seems about right

length(clean$agewed[clean$marital == 5])  # 1080 NA
sum(is.na(clean$agewed))  # 1080 NA

```

### Initial visualizations
```{r}
ggplot(clean, aes(x = agewed)) + geom_histogram(bins = 60)

age_by_mar <- ggplot(clean, aes(x = marital, y = agewed))

age_by_mar + geom_bar(stat = "identity")

age_by_mar + coord_flip() + geom_point()


## hi git

```


#### Step and bartMachine (by Kai)
```{r}
stopifnot(require(bartMachine))

cleaned <- gss[which(gss$agewed >= 12), ]

## count real number for each variable
t.cleaned <- as.data.frame(t(cleaned))
t.cleaned$numNA <- NA_real_
for (i in 1:1261) {    
  t.cleaned[i, "numNA"] <- sum(t.cleaned[i, 1:1161] >= 0, na.rm = T)
}
table(t.cleaned$numNA)
sum(t.cleaned$numNA > 500)

## choose variables with 1161 obs
cleaned.1161 <- as.data.frame(t(t.cleaned[which(t.cleaned$numNA == 1161), 1:1161]))

## remove admin variables: id - 11, year - 38, vpsu(?) - 1, vstrat(?) - 2
remove <- c(1, 2, 11, 38)
cleaned.1161 <- cleaned.1161[ , -remove]

# Step - lm
lm1 <- lm(agewed ~ ., data = cleaned.1161)
step.lm1 <- step(lm1, direction = "both", trace = F)
summary(step.lm1)

#BartMachine
set_bart_machine_num_cores(parallel::detectCores())
bartdata <- cleaned.1161
training <- bartdata[1:1000, ]
testing <- bartdata[1001:1161, ]
bart <- bartMachine(X = training[ , -52], y = training[ , 52])  #agewed = 847 in raw data-remove

bart

predictions <- predict(bart, new_data = testing[, -52])
summary(testing[ , 52] - predictions)

sd(testing[ , 52] - predictions)

result <- data.frame(testing[ , 52] - predictions)
colnames(result) <- "dif"
result$class <- ifelse(result$dif < -3 | result$dif > 3, 0, 1)
table(result$class)
```

